### ISSUE TITLE
Move contents of the StevenVolckaert.Libraries directory to a separate repository

### ISSUE THREAD

**Issue by stevenvolckaert** [stevenvolckaert/autodesk-inventor-powertools#3]
The `StevenVolckaert.Libraries` directory contains code that's reusable across other applications.
### Tasks
- [x] Move the contents to a separate GitHub repository;
- [x] Create and upload NuGet packages to the [nuget.org](https://www.nuget.org/packages) package feed; and
- [x] Consume them in the `StevenVolckaert.InventorPowerTools` project.
